apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-deployment
        image: jubbuseacrinmh.azurecr.io/__ENV__-frontend:__BUILD_ID__
        ports:
        - containerPort: 3000
  
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: frontend-app
